name: Lint

on:
  push:
    branches: [ js ]
  pull_request:
    branches: [ js ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Run lint
        run: ./gradlew ktlintCheck
