name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Run lint
        run: ./gradlew ktlintCheck

      - name: Run unit test
        run: ./gradlew :app:testReleaseUnitTest

      - name: Assemble
        run: ./gradlew :app:assembleRelease

      - name: Deploy apk
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 2
